apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: coredns-lb
  annotations:
    metallb.universe.tf/allow-shared-ip: coredns
spec:
  selector:
    k8s-app: kube-dns
  type: LoadBalancer 
  loadBalancerIP: 172.17.255.10
  ports:
  - port: 53
    protocol: TCP
