ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
  hosts:
    - name: chartmuseum.35.204.4.205.nip.io
      path: /
      tls: true
      tlsSecret: chartmuseum.35.204.4.205.nip.io
securityContext: {}
env:
  open:
    DISABLE_API: false
